version: 1
# 将信息传播到配置文件的跟日志记录器中
disable_existing_loggers: True

formatters:
  simple:
    format: "%(asctime)s - %(filename)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./logs/info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  data_info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./logs/data_info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./logs/error.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  data_logger:
    level: INFO
    handlers: [ console, data_info_file_handler ]
    # 打开日志记录器
    propagate: False

root:
  level: INFO
  handlers: [ console, info_file_handler, error_file_handler ]